name: Unittests

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Build and install
        run: pip install --verbose .

      - name: Test stage 0
        run: python tests/test_stage_0.py

      - name: Test stage 1
        run: python tests/test_stage_1.py
      
      - name: Test stage 2
        run: python tests/test_stage_2.py